### ISSUE TITLE
U+1F52B Water Pistol Emoji Redesigned Firearm

### ISSUE THREAD

**Issue by NikSavchenk0** [jdecked/twemoji#106]
the gun emoji was returned back into its rightful form: m1911
<img src="https://abs.twimg.com/responsive-web/client-web/1f52b.1465b29a.svg" width="25%">

**Comment by jdecked** [comment]
As mentioned here before, we can't just take emoji off websites that we don't have the license to use. We're also not interested in deviating from a representation that's in line with every other major emoji vendor.
