### ISSUE TITLE
Update legacy references to Twitter

### ISSUE THREAD

**Issue by pointydev** [jdecked/twemoji#19]
Just thought a list of legacy Twitter references (at least ones I've found) may be useful going forward:

- [x] Link in repository description - ~~"Emoji for (mostly) everyone."~~
- [x] LICENCE(?)
- [x] README.md
  - [x] Build status badge
  - [x] Licence reference(?)
- [x] CONTRIBUTING.md
  - [x] Licence reference (old repo)
- [x] FOLDERS.md 
  - [x] URLs pointing towards old gh-pages deployment
- [x] LEGACY.md
  - [x] URL fragments pointing to old repo
- [x] package.json
  - [x] New name?
- [x] component.json
  - [x] `"repository"`
  - [x] `"author"`(?)
- [ ] `jsdelivr` script URLs
  - [ ] index.html
  - [ ] src/templates/preview.html
  - [ ] src/test/preview-svg.html
  - [ ] src/test/preview.html

Thanks,
Elliott ~~(also, holding back tears and pleading face got [people split](https://twitter.com/DiscordPreviews/status/1640809457423732763) lol)~~

**Comment by jdecked** [comment]
Thank you! I hastily changed like half of these when setting up the fork but it appears I missed many. Feel free to PR to fix these. (For any you're not sure what to change it to, just ask in the PR and we'll figure it out.)

**Comment by BurAndBY** [comment]
For build status part, a Travis page needs to be created by the repository author

**Comment by jdecked** [comment]
FYI @pointydev I couldn't find any references to Twitter in the jsDelivr script URLs. If you can find otherwise, please reopen and LMK where.

**Comment by pointydev** [comment]
@jdecked Some jsDelivr links are still for the [package on npm controlled by Twitter](https://www.npmjs.com/package/twemoji), namely:
https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/index.html#L47 https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/README.md?plain=1#L18-L25 https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/scripts/create-dist#L63 https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/src/templates/preview.html#L28 https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/src/test/preview-svg.html#L28 https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/src/test/preview.html#L28

(can't reopen myself though 😅)

**Comment by jdecked** [comment]
> @jdecked Some jsDelivr links are still for the [package on npm controlled by Twitter](https://www.npmjs.com/package/twemoji), namely:
> 
> https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/index.html#L47
> 
> https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/README.md?plain=1#L18-L25
> 
> https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/scripts/create-dist#L63
> 
> https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/src/templates/preview.html#L28
> 
> https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/src/test/preview-svg.html#L28
> 
> https://github.com/jdecked/twemoji/blob/c69a9fd4baee54607d93c5475c999fbd15eca62e/src/test/preview.html#L28
> 
> (can't reopen myself though 😅)

Thanks! All of those reference `@twemoji/api` though, which is indeed what this package is published on NPM as.

**Comment by pointydev** [comment]
Ah, I missed the `@` and `/api`, seems good!
