### ISSUE TITLE
Images for future emojis?

### ISSUE THREAD

**Issue by pauldog** [jdecked/twemoji#40]
I have created a couple emojis that are not in any specification yet:

Panther: (derived from leopard)
<img src="https://github.com/jdecked/twemoji/assets/33497043/9e198519-b327-4263-b0a6-76e97ef42de6" width="300" height="300">
Table: (derived from chair)
<img src="https://github.com/jdecked/twemoji/assets/33497043/3f50bb7c-a4e4-4628-bf43-528eda65b932" width="300" height="300">

What's your opinion on expanding the emojis to basically include a picture for every common noun?

If the purpose of twemoji is to be used in all sorts of apps and games, this might be more useful than just limiting it to emojis in some arbitrary specification. For example, I am using twemoji as a way to turn text into illustrations so I need more than the current set.

We could place them in a custom-emoji folder.

Thoughts?

**Comment by HaNerW10** [comment]
Added in the link : [https://github.com/HaNerW10/Custom-Emojis-Twemoji-TTF/releases/tag/15.0.3.1](added ttf cett)

**Comment by jdecked** [comment]
This has been mentioned multiple times in issues as well as in the README: if you want emoji that aren't in the Unicode spec, you need to propose it to the Emoji Subcommittee, not here. Luckily submissions are open now for 17.0 so it's a good time for proposals over there!

We will never add non-standard emoji here. It just won't happen. We're a library that implements the standard only.
