### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by samber** [jdecked/twemoji#60]
You made a Github release for v15.0.2 but the version has not been released on npmjs.org :-(

**Comment by jdecked** [comment]
Are you sure you're looking in the right place? https://www.npmjs.com/package/@twemoji/api/v/15.0.2 😉

The package name was changed in 14.1.0.

**Comment by samber** [comment]
Oh! sorry for your inconvenience ;)

And thanks for updating this lovely project!
