### ISSUE TITLE
15.0.3 Images are not available via CDN

### ISSUE THREAD

**Issue by heladrion** [jdecked/twemoji#68]
Hello,

thank you for maintaining this package!

I'm using this script
https://cdn.jsdelivr.net/npm/@twemoji/api@latest/dist/twemoji.min.js

which referes at the top internally to this url
`base:"https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.0.3/assets/"`

Unfortunately at this URL are no images. Example:
https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.0.3/assets/svg/2764.svg

If I change the URL to use 15.0.2
https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.0.2/assets/svg/2764.svg
the image is there.

**Comment by Yoizen** [comment]
Same problem

**Comment by Nerixyz** [comment]
The `v15.0.3` tag is missing.

**Comment by jdecked** [comment]
Whoops, didn't realize delaying writing release notes would break anything. TIL. v15.0.3 tag is published; actual release notes will come when I have time.
