### ISSUE TITLE
My designs for the 15.1 smileys

### ISSUE THREAD

**Issue by bsoap-cat** [jdecked/twemoji#71]
![no](https://github.com/jdecked/twemoji/assets/127647009/b147c524-e45b-4eae-b92f-90a156143495)
![yes](https://github.com/jdecked/twemoji/assets/127647009/faa31c4b-e6d8-465b-9abf-6337486c779f)
I'm not that good at making svg art, so please excuse the lack of masks, using outlines for the face, etc.

Colors used:
#FCD824 (face color)
#4BB4F0 (movement color)
#694200 (despite picking this color out of immaturity, it works well as the color of the mouth and the eyes)

**Comment by jdecked** [comment]
superseded by/addressed in #78
