### ISSUE TITLE
Consider adding Custom Twemoji API as a community project

### ISSUE THREAD

**Issue by blakegearin** [jdecked/twemoji#76]
Hi, I'm the author and maintainer of Custom Twemoji API ([website](https://customtwemoji.com), [repo](https://github.com/custom-twemoji/custom-twemoji-api)). It's been around since 2021 and was inspired by the old account [EmojiMashupBot](https://twitter.com/emojimashupbot), which was/is closed source. I've been updating the API recently and plan to add v15 support soon. I still consider it in beta because I haven't gotten around to adding a staging environment (for stability) or an authentication layer (for visibility & security).

Thought it might be good to include in the [Community Projects section](https://github.com/jdecked/twemoji?tab=readme-ov-file#community-projects) of the README. If not, no worries, you can close this out.

Thank you for maintaining a fork.

**Comment by jdecked** [comment]
Cool project! Added to README. Feel free to make your own PR next time for an addition like this; it'll probably be quicker :)
