### ISSUE TITLE
Unicode 15.1

### ISSUE THREAD

**Issue by jdecked** [jdecked/twemoji#78]
Hello folks! We're currently working on [Unicode 15.1](https://www.unicode.org/emoji/charts-15.1/emoji-released.html) ([emoji test data](https://unicode.org/Public/emoji/15.1/emoji-test.txt)). You can track our progress on it in this issue. Help is welcome: feel free to comment on this issue if you're willing to create any of the unfinished SVGs in the table below. It's totally cool if two people want to work on the same emoji; we'll review all submissions before publishing.

## Unicode 15.1 To-Do Tracker
| № | Done | Unicode Codepoint | CLDR Short Name | Has Skin? | Category | Keywords | Designer |
|---|---|---|---|---|---|---|---|
| 1 | ✅ | 1f642-200d-2194-fe0f | Head shaking horizontally | ❌ | Smileys & Emotion | head shaking horizontally, no, shake | Gica (Discord) |
| 2 | ✅ | 1f642-200d-2195-fe0f | Head shaking vertically | ❌ | Smileys & Emotion | head shaking vertically, nod, yes | Gica (Discord) |
| 3 | ✅ | 1f6b6-200d-27a1-fe0f | Person walking facing right | ✅ | People & Body | | @Nerixyz |
| 4 | ✅ | 1f9ce-200d-27a1-fe0f | Person kneeling facing right | ✅ | People & Body | | @Nerixyz |
| 5 | ✅ | 1f9d1-200d-1f9af-200d-27a1-fe0f | Person with white cane facing right | ✅ | People & Body | | @Nerixyz |
| 6 | ✅ | 1f468-200d-1f9af-200d-27a1-fe0f | Man with white cane facing right | ✅ | People & Body | | @Nerixyz |
| 7 | ✅ | 1f469-200d-1f9af-200d-27a1-fe0f | Woman with white cane facing right | ✅ | People & Body | | @Nerixyz |
| 8 | ✅ | 1f9d1-200d-1f9bc-200d-27a1-fe0f | Person in motorized wheelchair facing right | ✅ | People & Body | | @Nerixyz |
| 9 | ✅ | 1f468-200d-1f9bc-200d-27a1-fe0f | Man in motorized wheelchair facing right | ✅ | People & Body | | @Nerixyz |
| 10 | ✅ | 1f469-200d-1f9bc-200d-27a1-fe0f | Woman in motorized wheelchair facing right | ✅ | People & Body | | @Nerixyz |
| 11 | ✅ | 1f9d1-200d-1f9bd-200d-27a1-fe0f | Person in manual wheelchair facing right | ✅ | People & Body | | @Nerixyz |
| 12 | ✅ | 1f468-200d-1f9bd-200d-27a1-fe0f | Man in manual wheelchair facing right | ✅ | People & Body | | @Nerixyz |
| 13 | ✅ | 1f469-200d-1f9bd-200d-27a1-fe0f | Woman in manual wheelchair facing right | ✅ | People & Body | | @Nerixyz |
| 14 | ✅ | 1f3c3-200d-27a1-fe0f | Person running facing right | ✅ | People & Body | | @Nerixyz |
| 15 | ✅ | 1f9d1-200d-1f9d1-200d-1f9d2 | Family: adult, adult, child | ❌ | People & Body | | Gica (Discord) |
| 16 | ✅ | 1f9d1-200d-1f9d1-200d-1f9d2-200d-1f9d2 | Family: adult, adult, child, child | ❌ | People & Body | | Gica (Discord) |
| 17 | ✅ | 1f9d1-200d-1f9d2 | Family: adult, child | ❌ | People & Body | | Gica (Discord) |
| 18 | ✅ | 1f9d1-200d-1f9d2-200d-1f9d2 | Family: adult, child, child | ❌ | People & Body | | Gica (Discord) |
| 19 | ✅ | 1f426-200d-1f525 | Phoenix | ❌ | Animals & Nature | fantasy, firebird, phoenix, rebirth, incarnation | Gica (Discord) |
| 20 | ✅ | 1f34b-200d-1f7e9 | Lime | ❌ | Food & Drink | citrus, fruit, lime, tropical | Gica (Discord) |
| 21 | ✅ | 1f344-200d-1f7eb | Brown mushroom | ❌ | Food & Drink | brown mushroom, food, fungus, nature, vegetable | @sofodesign |
| 22 | ✅ | 26d3-fe0f-200d-1f4a5 | Broken chain | ❌ | Objects | break, breaking, broken chain, chain, cuffs, freedom | Gica (Discord) |

**Comment by HaNerW10** [comment]
When will Unicode 15.1 come out?

**Comment by jdecked** [comment]
> When will Unicode 15.1 come out?

Current optimistic ETA is end of this week, but I'm currently down with a cold, so do note that is an _optimistic_ estimate.

**Comment by jdecked** [comment]
See [v15.1.0](https://github.com/jdecked/twemoji/releases/tag/v15.1.0). Please report any oddities in v15.1.0 by opening a new issue.

**Comment by Moise946** [comment]
I made some designs for the new emojis 
![Drawing-8 sketchpad (3)](https://github.com/jdecked/twemoji/assets/85855255/6c75b43f-cbbc-4186-a0bc-5412072752b1)
![Drawing-8 sketchpad (2)](https://github.com/jdecked/twemoji/assets/85855255/31be81a6-f4d2-46e1-8672-17f30ffe7038)
![Drawing-8 sketchpad (1)](https://github.com/jdecked/twemoji/assets/85855255/f7a1e1d1-bfd4-4b00-b01a-e52d110ba2c1)
![Drawing-8 sketchpad](https://github.com/jdecked/twemoji/assets/85855255/f112a09a-69f7-4254-b789-6db83d913db0)
![Drawing-7 sketchpad](https://github.com/jdecked/twemoji/assets/85855255/3fc299df-c7b6-454d-9919-a9458cccb9eb)
![Drawing-4 sketchpad](https://github.com/jdecked/twemoji/assets/85855255/43f846d3-f219-4e99-b75a-f18806416099)

**Comment by jdecked** [comment]
> I made some designs for some of the new emojis !

Thanks for your submission but we've already finalized the 15.1 emoji.
