### ISSUE TITLE
My designs for Emoji 15.1 

### ISSUE THREAD

**Issue by Moise946** [jdecked/twemoji#90]
Here are designs for the emojis in Emoji 15.1.
![Drawing-8 sketchpad (3)](https://github.com/jdecked/twemoji/assets/85855255/354021b2-5933-469c-b985-e22597045576)
![Drawing-8 sketchpad (2)](https://github.com/jdecked/twemoji/assets/85855255/df3fe2af-e9de-4de2-8291-991a4daafb2f)
![Drawing-8 sketchpad (1)](https://github.com/jdecked/twemoji/assets/85855255/7bea4f6c-b757-46b3-868d-2f768dd86470)
![Drawing-8 sketchpad](https://github.com/jdecked/twemoji/assets/85855255/0dc2a278-642f-4aa0-b10f-a741827d71bd)
![Drawing-7 sketchpad](https://github.com/jdecked/twemoji/assets/85855255/645732c4-d3f8-40fb-badf-3f0586a06f55)
![Drawing-4 sketchpad](https://github.com/jdecked/twemoji/assets/85855255/42d839ea-5da4-4399-9808-7f28c0e9ea9e)

They may be just recycled, I'm just trying ¯\_(ツ)_/¯

**Comment by jdecked** [comment]
Thanks for your submission, but we've already finalized and published the 15.1 emoji.
